baseurl = "https://amentalmodel.com/"
languageCode = "en-us"
title = "A Mental Model"
theme = "hugo-natrium-theme"
preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"
disqusShortname = "amentalmodel"

[taxonomies]
    category = "categories"
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110

[params]
    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
